### ISSUE TITLE
Where's My Money?

### ISSUE THREAD

**Issue by KitchM** [cutiepi-io/cutiepi-doc#14]
I have not heard back from you nor have I received my CutiePie.  Please send my refund ASAP.  Thank you.

**Comment by penk** [comment]
@KitchM hi thanks for reaching out, we have started shipping, if you'd like a refund please mail me your order email address & order number, or just direct message me on Telegram https://t.me/penkia, thanks!

**Comment by KitchM** [comment]
So if you are shipping, when do I get mine?
