### ISSUE TITLE
No virtual keyboard at the PIXEL desktop

### ISSUE THREAD

**Issue by Palmiga1** [cutiepi-io/cutiepi-doc#3]
There is no virtual keyboard at the Pixel desktop, but its promised in the stretch goals.
Need to install Onboard but its not very useabl.e

**Comment by penk** [comment]
Thanks for the report, this is a work-in-progress, should be available in future release soon. 
ref. https://twitter.com/penk/status/1493988424650428416

**Comment by PhoenixRion** [comment]
I also noticed that I cannot login without an external keyboard.  Would this be fixed by the same work or should I create a separate issue?

**Comment by penk** [comment]
@Palmiga1 Hi, we have a new nightly build which enabled virtual keyboard on PIXEL desktop for GTK and Qt application, this implementation reuses the same qtvirtualkeyboard package: 
![qvkb-desktop-2](https://user-images.githubusercontent.com/61878/160563563-6cd30421-34b5-4883-a6cf-13c4a3aab36c.png)

If you like to test, here's the download link:
```
file: image_2022-03-28-raspios-cutiepi.zip
download: https://drive.google.com/file/d/1l7YCtGOv36ABwo5QfTlVio3IW3FPSMnV/view
shasum: 5f94268991a389f1a89999dee997c188822a6123
```

**Comment by Palmiga1** [comment]
Thanks for the link. The keyboard works good for the Pixel-desktop. :-)
But i could not login, if I switch the auto-login off.

The screen-keyboard is not working in the login-screen. 
Even a normal keyboard, connected to the USB-port is not working correct, or did you change the standard-password?

**Comment by penk** [comment]
@Palmiga1 thank you for the test! I don't know too much about the login screen, but maybe that lightdm was not designed with touch or keyboard in mind. the password is default `raspberry`. Perhaps we can switch to SSDM or GDM for better touch support? 

Here's a new build (fixed the annoying predictive text & added Ctrl key to terminal layout): 
https://drive.google.com/file/d/1xMCnQs4wtblL698N_S9MgZ8WGowoTmht/view?usp=sharing

**Comment by penk** [comment]
Let me close this one for now with the new image release
https://github.com/cutiepi-io/pi-gen_stage4.5-cutiepi/releases/tag/2022-04-01
