### ISSUE TITLE
Unhelpful intelligence on WiFi password input

### ISSUE THREAD

**Issue by forbesmyester** [cutiepi-io/cutiepi-doc#7]
I have a password which when I input, using the shell's WiFi control causes spaces to be automatically inserted.

It's quite a symbol heavy password, but I think it occurs after a `#`.

**Comment by penk** [comment]
Thank you for the report, I'll work on this.

**Comment by penk** [comment]
Fixed in the latest image
https://github.com/cutiepi-io/pi-gen_stage4.5-cutiepi/releases/tag/2022-04-01
